
name: Convert M3U to TXT

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - 'mig2.txt'  # 当mig2.txt文件有变更时自动运行

jobs:
  convert-m3u:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Convert M3U to TXT format
      id: convert
      run: |
        echo "开始转换M3U格式到标准TXT格式..."
        
        # 检查源文件是否存在
        if [ ! -f "mig2.txt" ]; then
          echo "错误：mig2.txt 文件不存在"
          exit 1
        fi
        
        # 读取并转换文件
        input_file="mig2.txt"
        output_file="converted_channels.txt"
        
        # 创建Python转换脚本
        python_script="m3u_converter.py"
        
        cat > $python_script << 'EOF'
import re
import os
import sys

def convert_m3u_to_txt(input_file, output_file):
    """
    将M3U格式转换为标准TXT频道列表
    格式：频道名称 | 播放URL
    """
    try:
        print(f"正在转换 {input_file} -> {output_file}")
        
        # 读取输入文件
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        lines = content.split('\n')
        output_lines = []
        channel_name = ''
        channel_count = 0
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
                
            # 处理频道信息行
            if line.startswith('#EXTINF:'):
                # 提取频道名称
                match = re.search(r'#EXTINF:-?\d+,(.*)', line)
                if match:
                    channel_name = match.group(1).strip()
                    # 清理特殊字符
                    channel_name = re.sub(r'[^\w\s\u4e00-\u9fa5\-_]', '', channel_name)
                    channel_name = channel_name.replace('|', '-')
                
            # 处理URL行
            elif line.startswith('http'):
                if channel_name:
                    output_lines.append(f"{channel_name} | {line}")
                    channel_count += 1
                    channel_name = ''
        
        # 写入输出文件
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('# 标准TXT格式频道列表\n')
            f.write(f'# 总频道数: {channel_count}\n')
            f.write('# 格式: 频道名称 | 播放URL\n')
            f.write('# 生成时间: ' + sys.argv[1] + '\n')
            f.write('\n'.join(output_lines))
        
        print(f"转换完成！共转换 {channel_count} 个频道")
        return channel_count
        
    except Exception as e:
        print(f"转换错误: {e}")
        return 0

if __name__ == "__main__":
    import datetime
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    input_file = "mig2.txt"
    output_file = "converted_channels.txt"
    
    channel_count = convert_m3u_to_txt(input_file, output_file)
    
    # 设置GitHub Actions输出
    with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
        f.write(f"channel_count={channel_count}\n")
        if channel_count > 0:
            f.write("conversion_success=true\n")
        else:
            f.write("conversion_success=false\n")
EOF

        # 运行转换脚本
        timestamp=$(date '+%Y-%m-%d %H:%M:%S')
        python $python_script "$timestamp"
        
        # 检查转换是否成功
        if [ -f "$output_file" ]; then
            file_size=$(stat -f%z "$output_file" 2>/dev/null || stat -c%s "$output_file")
            channel_count=$(grep -c " | http" "$output_file" || 0)
            echo "转换成功！输出文件: $output_file"
            echo "文件大小: $file_size 字节"
            echo "频道数量: $channel_count"
            
            # 设置输出变量
            echo "::set-output name=converted_file::$output_file"
            echo "::set-output name=total_channels::$channel_count"
        else
            echo "转换失败：输出文件未生成"
            exit 1
        fi
    
    - name: Create conversion report
      if: steps.convert.outputs.total_channels > 0
      run: |
        echo "# M3U转换报告" > conversion_report.md
        echo "" >> conversion_report.md
        echo "## 转换详情" >> conversion_report.md
        echo "- 源文件: mig2.txt" >> conversion_report.md
        echo "- 输出文件: ${{ steps.convert.outputs.converted_file }}" >> conversion_report.md
        echo "- 频道总数: ${{ steps.convert.outputs.total_channels }}" >> conversion_report.md
        echo "- 转换时间: $(date '+%Y-%m-%d %H:%M:%S')" >> conversion_report.md
        echo "" >> conversion_report.md
        echo "## 文件信息" >> conversion_report.md
        echo "\`\`\`" >> conversion_report.md
        head -10 "${{ steps.convert.outputs.converted_file }}" >> conversion_report.md
        echo "..." >> conversion_report.md
        echo "\`\`\`" >> conversion_report.md
    
    - name: Commit converted files
      if: steps.convert.outputs.total_channels > 0
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add converted_channels.txt conversion_report.md
        git commit -m "Auto-convert M3U to TXT format [skip ci]

        # 检查是否有变更需要提交
        if git diff --quiet HEAD~1; then
          echo "没有新的变更需要提交"
        else
          git push
          echo "已提交转换结果"
        fi
    
    - name: Upload conversion artifacts
      if: steps.convert.outputs.total_channels > 0
      uses: actions/upload-artifact@v4
      with:
        name: converted-channels
        path: |
          converted_channels.txt
          conversion_report.md
<code_end>
<code_start project_name=M3U转换工作流 filename=m3u_converter.py title=独立的M3U转换Python脚本 entrypoint=false runnable=true project_final_file=true>
#!/usr/bin/env python3
"""
M3U格式转换器
将M3U格式的播放列表转换为标准的TXT频道列表
"""

import re
import os
import sys
from datetime import datetime

class M3UConverter:
    def __init__(self):
        self.channel_count = 0
        self.valid_channels = 0
    
    def clean_channel_name(self, name):
        """清理频道名称中的特殊字符"""
        # 保留中文、英文、数字、空格和常用符号
        cleaned = re.sub(r'[^\w\s\u4e00-\u9fa5\-_]', '', name)
        cleaned = cleaned.replace('|', '-').strip()
        return cleaned
    
    def parse_m3u_file(self, input_file):
        """解析M3U文件并返回频道列表"""
        channels = []
        
        try:
            with open(input_file, 'r', encoding='utf-8') as f:
                content = f.read()
            
            lines = content.split('\n')
            current_channel = {}
            
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                
                # M3U文件头
                if line == '#EXTM3U':
                    continue
                
                # 频道信息行
                if line.startswith('#EXTINF:'):
                    # 提取频道名称和可能的其他信息
                    match = re.search(r'#EXTINF:-?\d+,(.*)', line)
                    if match:
                        current_channel['name'] = self.clean_channel_name(match.group(1))
                
                # URL行
                elif line.startswith('http'):
                    if current_channel and 'name' in current_channel:
                        current_channel['url'] = line
                        channels.append(current_channel.copy())
                        current_channel = {}
            
            self.channel_count = len(channels)
            return channels
            
        except Exception as e:
            print(f"解析M3U文件错误: {e}")
            return []
    
    def convert_to_txt(self, input_file, output_file):
        """主转换函数"""
        print(f"开始转换M3U文件: {input_file}")
        
        # 检查输入文件
        if not os.path.exists(input_file):
            print(f"错误：输入文件 {input_file} 不存在")
            return False
        
        # 解析M3U文件
        channels = self.parse_m3u_file(input_file)
        
        if not channels:
            print("错误：未找到有效频道或文件格式不正确")
            return False
        
        # 生成输出内容
        output_lines = []
        output_lines.append('# 标准TXT格式频道列表')
        output_lines.append(f'# 生成时间: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")')
        output_lines.append(f'# 总频道数: {len(channels)}')
        output_lines.append('# 格式: 频道名称 | 播放URL')
        output_lines.append('')
        
        for channel in channels:
            output_lines.append(f"{channel['name']} | {channel['url']}")
        
        # 写入输出文件
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(output_lines))
        
        print(f"转换完成！")
        print(f"输入文件: {input_file}")
        print(f"输出文件: {output_file}")
        print(f"转换频道数: {len(channels)}")
        
        return True

def main():
    if len(sys.argv) != 3:
        print("用法: python m3u_converter.py <输入文件> <输出文件>")
        print("示例: python m3u_converter.py mig2.txt channels.txt")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    converter = M3UConverter()
    success = converter.convert_to_txt(input_file, output_file)
    
    if success:
        sys.exit(0)
    else:
        sys.exit(1)

if __name__ == "__main__":
    main()

